apiVersion: v1
kind: Service

metadata:
  name: grpc-chatbot-service

spec:
  type: LoadBalancer

  selector:
    app: grpc-chatbot

  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051